version: '3'
services:
  zookeeper:
    image: zookeeper:3.5
    container_name: zookeeper
    ports:
      - 2181:2181

  kafka101:
    image: confluentinc/cp-kafka:5.1.0
    container_name: kafka101
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 101
      KAFKA_LISTENERS: INTERNAL_LISTENER://0.0.0.0:19092,EXTERNAL_LISTENER://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: INTERNAL_LISTENER://kafka101:19092,EXTERNAL_LISTENER://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL_LISTENER:PLAINTEXT,EXTERNAL_LISTENER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL_LISTENER
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_DELETE_TOPIC_ENABLE: 'true'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 2
    depends_on:
      - zookeeper

  kafka102:
    image: confluentinc/cp-kafka:5.1.0
    container_name: kafka102
    ports:
      - 9093:9093
    environment:
      KAFKA_BROKER_ID: 102
      KAFKA_LISTENERS: INTERNAL_LISTENER://0.0.0.0:19093,EXTERNAL_LISTENER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: INTERNAL_LISTENER://kafka102:19093,EXTERNAL_LISTENER://localhost:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL_LISTENER:PLAINTEXT,EXTERNAL_LISTENER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL_LISTENER
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_DELETE_TOPIC_ENABLE: 'true'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 2
    depends_on:
      - zookeeper

  kafka103:
    image: confluentinc/cp-kafka:5.1.0
    container_name: kafka103
    ports:
      - 9094:9094
    environment:
      KAFKA_BROKER_ID: 103
      KAFKA_LISTENERS: INTERNAL_LISTENER://0.0.0.0:19094,EXTERNAL_LISTENER://0.0.0.0:9094
      KAFKA_ADVERTISED_LISTENERS: INTERNAL_LISTENER://kafka103:19094,EXTERNAL_LISTENER://localhost:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL_LISTENER:PLAINTEXT,EXTERNAL_LISTENER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL_LISTENER
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_DELETE_TOPIC_ENABLE: 'true'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 2
    depends_on:
      - zookeeper

  kafka-manager:
    image: sheepkiller/kafka-manager
    container_name: kafka-manager
    ports:
      - 9000:9000
    environment:
      ZK_HOSTS: zookeeper:2181